# Complete StrataRegula Security Patterns
# Distribution URL: https://patterns.security-audit.io/api/v1/rulesets/all.toml
# Version: 1.0.0
# Updated: 2025-08-31

title = "StrataRegula Complete Security Patterns"

[extend]
useDefault = true

# Allowlist for false positives
[[allowlist]]
description = "Ignore test fixtures and examples"
paths = [
    '''tests/fixtures/.*''',
    '''examples/.*''',
    '''docs/.*\.md''',
    '''\.nyc_output/.*''',
    '''coverage/.*''',
    '''logs/.*''',
    '''reports/.*''',
    '''\.cache/.*''',
]

[[allowlist]]
description = "Ignore GitHub Actions secrets (legitimate usage)"
regexes = [
    '''secrets\.GITHUB_TOKEN''',
    '''secrets\.CLAUDE_CODE_OAUTH_TOKEN''',
]

[[allowlist]]
description = "Ignore documentation sample tokens and test examples"
regexes = [
    '''ghp_1234567890123456789012345678901234567890''',
    '''AKIAIOSFODNN7EXAMPLE''',
    '''sk-1234567890123456789012345678901234567890123456789012345678''',
    '''eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9\..*''',
    '''ghp_.*fake.*''',
    '''sk-.*fake.*''',
    '''test.*token.*''',
]

# GitHub Patterns
[[rules]]
id = "strataregula-github-pat"
description = "GitHub Personal Access Token"
regex = '''ghp_[A-Za-z0-9_]{36}'''
tags = ["github", "token", "pat"]

[[rules]]
id = "strataregula-github-oauth"
description = "GitHub OAuth Token"
regex = '''gho_[A-Za-z0-9_]{36}'''
tags = ["github", "oauth", "token"]

[[rules]]
id = "strataregula-github-user-to-server"
description = "GitHub User-to-Server Token"
regex = '''ghu_[A-Za-z0-9_]{36}'''
tags = ["github", "user-to-server", "token"]

[[rules]]
id = "strataregula-github-server-to-server"
description = "GitHub Server-to-Server Token"
regex = '''ghs_[A-Za-z0-9_]{36}'''
tags = ["github", "server-to-server", "token"]

# AWS Patterns
[[rules]]
id = "strataregula-aws-access-key"
description = "AWS Access Key ID"
regex = '''AKIA[0-9A-Z]{16}'''
tags = ["aws", "access-key"]

[[rules]]
id = "strataregula-aws-secret-key"
description = "AWS Secret Access Key"
regex = '''(?i)aws(.{0,20})?['"][0-9a-zA-Z/+=]{40}['"]'''
tags = ["aws", "secret-key"]

# OpenAI & AI Services
[[rules]]
id = "strataregula-openai-api-key"
description = "OpenAI API Key"
regex = '''sk-[a-zA-Z0-9]{48}'''
tags = ["openai", "api-key"]

[[rules]]
id = "strataregula-anthropic-api-key"
description = "Anthropic Claude API Key"
regex = '''sk-ant-api[0-9]{2}-[A-Za-z0-9\-_]{95}'''
tags = ["anthropic", "claude", "api-key"]

# Communication Platforms
[[rules]]
id = "strataregula-slack-bot-token"
description = "Slack Bot Token"
regex = '''xoxb-[0-9]{10,13}-[0-9]{10,13}-[a-zA-Z0-9]{24}'''
tags = ["slack", "bot", "token"]

[[rules]]
id = "strataregula-slack-webhook"
description = "Slack Webhook URL"
regex = '''https://hooks\.slack\.com/services/[A-Z0-9]{9}/[A-Z0-9]{9}/[A-Za-z0-9]{24}'''
tags = ["slack", "webhook"]

# Generic Tokens
[[rules]]
id = "strataregula-jwt-token"
description = "JWT Token"
regex = '''eyJ[A-Za-z0-9_=-]+\.[A-Za-z0-9_=-]+\.?[A-Za-z0-9_.+/=-]*'''
tags = ["jwt", "token"]

[[rules]]
id = "strataregula-bearer-token"
description = "Bearer Token"
regex = '''(?i)bearer\s+[a-zA-Z0-9\-_.+/=]{20,}'''
tags = ["bearer", "token", "authorization"]

# Cryptographic Material
[[rules]]
id = "strataregula-private-key"
description = "Private Key (PEM format)"
regex = '''-----BEGIN\s+(RSA\s+)?PRIVATE\s+KEY-----'''
tags = ["private-key", "pem", "rsa"]

[[rules]]
id = "strataregula-ssh-key"
description = "SSH Private Key"
regex = '''-----BEGIN\s+OPENSSH\s+PRIVATE\s+KEY-----'''
tags = ["ssh", "private-key", "openssh"]

# Generic Secret Patterns
[[rules]]
id = "strataregula-generic-secret"
description = "Generic Secret Pattern"
regex = '''(?i)(password|passwd|pwd|secret|token|key|api[_-]?key)[\s:='"]{1,3}[a-zA-Z0-9\-_.+/=]{8,45}'''
tags = ["generic", "secret", "password"]

# Database Connection Strings
[[rules]]
id = "strataregula-database-url"
description = "Database Connection String"
regex = '''(?i)(mysql|postgres|mongodb|redis)://[a-zA-Z0-9\-_.+%]+:[a-zA-Z0-9\-_.+%]+@[a-zA-Z0-9\-_.+]+:[0-9]+/[a-zA-Z0-9\-_.+]+'''
tags = ["database", "connection-string"]

# Cloud Provider Keys
[[rules]]
id = "strataregula-google-api-key"
description = "Google API Key"
regex = '''AIza[0-9A-Za-z\-_]{35}'''
tags = ["google", "api-key"]

[[rules]]
id = "strataregula-azure-key"
description = "Azure Subscription Key"
regex = '''[0-9a-f]{32}'''
tags = ["azure", "subscription-key"]

# Payment Service Keys
[[rules]]
id = "strataregula-stripe-key"
description = "Stripe API Key"
regex = '''(?i)sk_live_[0-9a-zA-Z]{24}'''
tags = ["stripe", "api-key", "live"]

[[rules]]
id = "strataregula-stripe-test-key"
description = "Stripe Test API Key"
regex = '''(?i)sk_test_[0-9a-zA-Z]{24}'''
tags = ["stripe", "api-key", "test"]

# StrataRegula Specific Patterns
[[rules]]
id = "strataregula-custom-token"
description = "StrataRegula Custom Token Pattern"
regex = '''(?i)sr[_-]?(token|key|secret)[\s:='"]{1,3}[a-zA-Z0-9\-_.+/=]{16,}'''
tags = ["strataregula", "custom", "token"]