name: flaky-rehab
on:
  schedule:
    - cron: '0 0 * * MON'  # JST Monday 09:00 AM
  workflow_dispatch:
jobs:
  rehab:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - name: Install deps (best-effort)
        run: |
          pip install -U pip pytest pyyaml || true
          if [ -f requirements.txt ]; then pip install -r requirements.txt || true; fi
          if [ -f pyproject.toml ]; then pip install uv && uv sync || true; fi
      - name: Run flaky rehabilitation
        run: |
          python tools/rehab_flaky.py
          echo "Rehabilitation complete"
      - name: Check for changes
        id: changes
        run: |
          if git diff --quiet tests/flaky_quarantine.yaml; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi
      - name: Commit and create PR
        if: steps.changes.outputs.changed == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "chore(flaky): rehab passed cases - 10 consecutive runs"
          title: "chore(flaky): automatic rehabilitation of stable tests"
          body: |
            ## Flaky Test Rehabilitation Results
            
            This PR automatically removes tests from quarantine that passed 10 consecutive runs.
            
            **What changed:**
            - Tests removed from `tests/flaky_quarantine.yaml`
            - These tests are now back in active CI validation
            
            **Safety:**
            - All removed tests passed 10 consecutive runs
            - If instability returns, they will be re-quarantined automatically
            
            🤖 Generated by flaky-rehab workflow
          branch: "chore/flaky-rehab"
          delete-branch: true